version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Lee289473007216!
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: UserSecurePass123!
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "user",
          "-pUserSecurePass123!",
        ]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s

  backend:
    build:
      context: ./backend
    container_name: posture-app-backend
    restart: always
    volumes:
      - ./backend:/app
      - /app/__pycache__
      - /app/.pytest_cache
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: UserSecurePass123!
      DB_NAME: testdb
      # 추가 환경 변수
      SECRET_KEY: posture-app-secret-key-2024
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      timeout: 10s
      retries: 5
      interval: 30s
      start_period: 40s

volumes:
  db_data:
