[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python migrate_db.py && python main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
USE_LOCAL_CONFIG = "false"
